#pragma config(Sensor, S1,     ,               sensorSONAR)
#pragma config(Sensor, S2,     1,              sensorSONAR)
#pragma config(Sensor, S3,     2,              sensorSONAR)
#pragma config(Sensor, S4,     3,              sensorTouch)
#pragma config(Motor,  motorA,          A,             tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          E,             tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          D,             tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define VelocidadeMax 100
#define VelocidadeAjuste 60

float kVelocidade = 3;

#include "includes/configurarVariaveis.h"
#include "includes/configuracaoManual.h"
#include "includes/atualizarDisplay.h"
//#include "filtrarSensor.h"
#include "visao/filtroMediaMovel.h"
#include "visao/tratamentoSensores.h"
#include "includes/monitoramento.h"
#include "movimentacao/Padrao.h"
#include "estrategias/Inicial.h"

task AtualizarSensores();
task SimularSensores();

task main()
{
	//setBluetoothOn();
	//btConnect(1, "RINO");
	clearDebugStream();

	ConfigurarVariaveis();
		StartTask(AtualizarSensores);
	Esperar = GerarMenu(Esperar5s, 2);
	EstrategiaSelecionada = GerarMenu(Estrategias, NumEstrategias);
	PressioneStart();

	if(Esperar){
		FuncaoEsperar();
	}

	nSyncedMotors = synchBC;
	ClearTimer(T1);
	ClearTimer(T2);
	ClearTimer(T3);

	//int contador = 0;

	//StartTask(Monitoramento);
	StartTask(AtualizarDisplay);

	//StartTask(SimularSensores);
	StartTask(TratarSensores);

	//eraseDisplay();

	iniciarEstrategia();

	while(time1[T4] < 5000){};
	while (SensorToque != false){};


	StartTask(Movimentacao);

	while(true){
		if(SensorToque){
			break;
		}
		/*contador++;
		if(time1[T3] >= 1000){
		writeDebugStream("Ciclos = %d",contador);
		break;
		}*/
	}
}

//=========================================================================================================================

task AtualizarSensores(){
	bool simular = false;
	while(true){
		FiltrarSensor(SonarEsquerdo, simular);
		FiltrarSensor(SonarDireito, simular);
		FiltrarSensor(SonarCentro, simular);
		SensorToque = SensorValue[S4];
		writeDebugStream("%d\n", SensorToque);
		//ProcessarAcelerometro();
	}
}

task SimularSensores(){
	int min = 50;
	int max = 150;

	srand(nSysTime);

	while(true)
	{
		if(nNxtButtonPressed == BotaoLaranja){
			NovoValor = 20;
		}
		else{
			NovoValor = 255;
		}
		//NovoValor = (rand() % (max-min)) + min;
		//wait1Msec(77);
	}
}
