#pragma config(Sensor, S1,     0,              sensorSONAR)
#pragma config(Sensor, S2,     1,               sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard

#define SonarEsquerdo 0
#define SonarDireito 1
#define SonarCentro 2
#define NumSensores 3

#define Frente 0
#define Direita 1
#define Esquerda 2
#define ProcurarDireita 3
#define ProcurarEsquerda 4

#define NumMenus 2
#define NumEstrategias 4
#define BotaoDireito 1
#define BotaoEsquerdo 2
#define BotaoLaranja 3
#define Estrategias 0
#define Padrao 0
#define Esperar5s 1

#define Botoes 1
#define Display1 2
#define Display2 3

int ValorSensor[NumSensores];
int StatusSonar = 0;
int EstrategiaSelecionada = -1;
int Esperar = 0;
int CategoriaMensagem = -1;
int Botao = -1;

string Espaco[2];
string StatusDisplay[5];
string ConfigMenu[2];
string Menus[NumMenus][5];

void VetorStatus(){
	StatusDisplay[Frente] = "Frente";
	StatusDisplay[Direita] = "Direita";
	StatusDisplay[Esquerda] = "Esquerda";
	StatusDisplay[ProcurarDireita] = "Procurar Direita";
	StatusDisplay[ProcurarEsquerda] = "Procurar Esquerda";

	ConfigMenu[1] = "->";
	ConfigMenu[0] = "  ";

	Menus[Estrategias][0] = "Estrategia";
	Menus[Estrategias][1] = "Padrao";
	Menus[Estrategias][2] = "Bora Fazer";
	Menus[Estrategias][3] = "Num tem";
	Menus[Estrategias][4] = "Outra Estrategia";

	Menus[Esperar5s][0] = "Esperar 5s?";
	Menus[Esperar5s][1] = "Nao";
	Menus[Esperar5s][2] = "Sim";
}

void DarEspaco(int Sensor, int aux){
	if(ValorSensor[Sensor] < 100){
		Espaco[aux] = " ";
	}
	else{
		Espaco[aux] = "";
	}
}

task AtualizarDisplay(){
	while(true){
		nxtDisplayCenteredBigTextLine(0, "#GoRino");
		nxtDisplayCenteredTextLine(3, "Status Sonar:");
		nxtDisplayCenteredTextLine(4, "%s", StatusDisplay[StatusSonar]);
		nxtDisplayCenteredTextLine(5, "Center");
		DarEspaco(SonarCentro, 0);
		nxtDisplayTextLine(6, "Left  %s%d   Right", Espaco[0], ValorSensor[SonarCentro]);
		DarEspaco(SonarEsquerdo, 0);
		DarEspaco(SonarDireito, 1);
		nxtDisplayTextLine(7, "%s%d          %s%d", Espaco[0], ValorSensor[SonarEsquerdo], Espaco[1]
		, ValorSensor[SonarDireito]);
		wait10Msec(10);
	}
}


int GerarMenu(int TipoMenu, int NumOpcoes){
	bool PrimeiraVez = true;
	int Posicao = 0;
	bool ColocarSeta = 0;
	bool PularLinha = false;
	if(NumOpcoes == 2){
		PularLinha = true;
	}
	while(true){
		if(Botao != -1 || PrimeiraVez == true){
			PrimeiraVez = false;
			if(Botao == BotaoLaranja){
				eraseDisplay();
				Botao = -1;
				return Posicao;
			}
			else if(Botao == BotaoDireito){
				Posicao++;
				if(Posicao >= NumOpcoes){
					Posicao = 0;
				}
				Botao = -1;
			}
			else if(Botao == BotaoEsquerdo){
				Posicao--;
				if(Posicao < 0){
					Posicao = NumOpcoes - 1;
				}
				Botao = -1;
			}
			eraseDisplay();
			nxtDisplayCenteredBigTextLine(0, "#GoRino");
			nxtDisplayTextLine(3, "%s:", Menus[TipoMenu][0]);
			for(int Linha = 0; Linha < NumOpcoes; Linha++){
				if(Posicao == Linha){
					ColocarSeta = true;
				}
				else{
					ColocarSeta = false;
				}
				nxtDisplayTextLine(Linha + 4 + PularLinha, "%s%s", ConfigMenu[ColocarSeta], Menus[TipoMenu][Linha + 1]);
			}
			while(nNxtButtonPressed != -1){};
		}
	}
}

void FuncaoEsperar(){
	ClearTimer(T4);
	int Segundos = 0;
	int Decimos = 0;
	while(time1[T4] < 5000){
		Segundos = time100[T4]/10;
		Decimos = time100[T4] - Segundos*10;
		//eraseDisplay();
		nxtDisplayCenteredBigTextLine( 0, "#GoRino");
		nxtDisplayCenteredTextLine(2, "%d,%d", Segundos, Decimos);
		wait10Msec(10);
	}
}

void PressioneStart(){
	nxtDisplayCenteredBigTextLine(0, "#GoRino");
	nxtDisplayCenteredTextLine(4, "Pressione");
	nxtDisplayCenteredBigTextLine(5, "[START]");
	while(Botao != BotaoLaranja){};
	eraseDisplay();
}

task Bluetooth(){
	while(true){
		CategoriaMensagem = message;
		if(CategoriaMensagem == Botoes){
			Botao = messageParm[1];
			ClearMessage();
		}
		else if(CategoriaMensagem == Display1){
			ValorSensor[SonarEsquerdo] = messageParm[1];
			ValorSensor[SonarCentro] = messageParm[2];
			ClearMessage();
		}
		else if(CategoriaMensagem == Display2){
			ValorSensor[SonarDireito] = messageParm[1];
			StatusSonar = messageParm[2];
			ClearMessage();
		}
		wait10Msec(10);
	}
}


task main()
{
	VetorStatus();

	StartTask(Bluetooth);

	Esperar = GerarMenu(Esperar5s, 2);
	EstrategiaSelecionada = GerarMenu(Estrategias, NumEstrategias);
	PressioneStart();

	ClearTimer(T1);
	ClearTimer(T2);
	ClearTimer(T3);
	ClearTimer(T4);

	StartTask(AtualizarDisplay);

	if(Esperar){
		FuncaoEsperar();
	}

	eraseDisplay();

	while(true){

	}
}
