#pragma config(Sensor, S1,     0,               sensorSONAR)
#pragma config(Sensor, S2,     1,              sensorSONAR)
#pragma config(Sensor, S3,     2,              sensorSONAR)
#pragma config(Sensor, S4,     3,            	sensorSONAR)
#pragma config(Motor,  motorA,          A,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          E,             tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          D,             tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define VelocidadeMax 100
#define kVelocidade 4

#include "includes/configurarVariaveisKowalski.h"
#include "includes/configuracaoManual.h"
#include "includes/atualizarDisplayKowalski.h"
//#include "filtrarSensor.h"
#include "visao/filtroKowalski.h"
#include "visao/tratamentoSensoresKowalski.h"
//#include "tratamentoSensoresKowalski.h"
//#include "monitoramento.h"
#include "movimentacao/Kowalski.h"
#include "estrategias/InicialKowalski.h"
#include "estrategias/PadraoKowalski.h"

task AtualizarSensores();
task SimularSensores();

void cair2(int TempoCaida){
	nSyncedMotors = synchBC;
	nSyncedTurnRatio = 100;
	MotorEsquerdo = 100;
	wait1Msec(TempoCaida);
	MotorEsquerdo = -100;
	wait1Msec(440);
}

task main()
{
	bPlaySounds = true;
	UnmuteSound();
	nVolume = 4;
	setBluetoothOn();
	btConnect(1, "NXT");
	clearDebugStream();
	ClearTimer(T1);

	ConfigurarVariaveis();
	Esperar = GerarMenu(Esperar5s, 2);
	movimentacaoInicial = GerarMenu(movInicial, 4);
	//EstrategiaSelecionada = GerarMenu(Estrategias, NumEstrategias);
	PressioneStart();

	//StartTask(Monitoramento);
	StartTask(AtualizarDisplay);
	StartTask(AtualizarSensores);
	//StartTask(SimularSensores);
	StartTask(TratarSensores);

	if(Esperar){
		FuncaoEsperar();
	}
	cair2(140);
	motor[A] = 100;
	iniciarMovimentacaoInicial();
	iniciarEstrategia();

	StartTask(Movimentacao);

	while(true){}
}

//==========================FUNCOES=================================

task AtualizarSensores(){
	bool simular = false;
	while(true){
		FiltrarSensor(SonarEsquerdo, simular);
		FiltrarSensor(SonarDireito, simular);
		FiltrarSensor(SonarEsquerdoFrente, simular);
		FiltrarSensor(SonarDireitoFrente, simular);
		//ProcessarAcelerometro();
	}
}

task SimularSensores(){
	int min = 50;
	int max = 150;

	srand(nSysTime);

	while(true)
	{
		if(nNxtButtonPressed == BotaoLaranja){
			NovoValor = 255;
		}
		else{
			NovoValor = 80;
		}
		//NovoValor = (rand() % (max-min)) + min;
		//wait1Msec(77);
	}
}
