
#pragma config(Sensor, S1,     0,              sensorSONAR)
#pragma config(Sensor, S2,     1,              sensorSONAR)
#pragma config(Sensor, S3,     2,              sensorSONAR)
#pragma config(Sensor, S4,     3,              sensorI2CHiTechnicAccel)
#pragma config(Motor,  motorA,          A,             tmotorNXT, openLoop, reversed, encoder)
#pragma config(Motor,  motorB,          E,             tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          D,             tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define VelocidadeMax 100

float kVelocidade = 4.51;

#include "includes/configurarVariaveis.h"
#include "includes/configuracaoManual.h"
#include "includes/atualizarDisplay.h"
//#include "filtrarSensor.h"
#include "visao/filtroMediaMovel.h"
#include "visao/tratamentoSensoresNeguito.h"
#include "includes/monitoramento.h"
#include "movimentacao/Padrao.h"
//#include "movimentacao/Curvatura.h"
#include "estrategias/Neguito.h"
#include "estrategias/Inicial.h"

task AtualizarSensores();
task SimularSensores();
task detectarCaidaRampa();

task main()
{
	bPlaySounds = true;
	UnmuteSound();
	nVolume = 4;
	setBluetoothOn();
	btConnect(1, "NXT");
	clearDebugStream();
	ClearTimer(T1);

	ConfigurarVariaveis();
	configurarEstrategias();
	Esperar = GerarMenu(Esperar5s, 2);
	movimentacaoInicial = GerarMenu(movInicial, 4);
	EstrategiaSelecionada = GerarMenu(Estrategias, NumEstrategias);
	PressioneStart();

	//StartTask(Monitoramento);
	StartTask(AtualizarDisplay);
	StartTask(AtualizarSensores);
	//StartTask(SimularSensores);
	StartTask(TratarSensores);

	if(Esperar){
		FuncaoEsperar();
	}

	ClearTimer(T3);

	StartTask(detectarCaidaRampa);
	motor[A] = -50;
	iniciarMovimentacaoInicial();
	iniciarEstrategia();

	StartTask(Movimentacao);

	while(true)
	{
	}
}

//==========================FUNCOES=================================

task AtualizarSensores(){
	bool simular = false;
	while(true){
		FiltrarSensor(SonarEsquerdo, simular);
		FiltrarSensor(SonarDireito, simular);
		FiltrarSensor(SonarCentro, simular);
		//ProcessarAcelerometro();
	}
}

task detectarCaidaRampa(){
	rampaCaiu = false;
	nMotorEncoder[A] = 0;
	while(nMotorEncoder[A] > -100){
		print("Angulo Rampa = %d\n", nMotorEncoder[A]);
		wait10Msec(1);
	}
	print("\nTempo de caida = %d\n", time1[T3]);
	rampaCaiu = true;
}

task SimularSensores(){
	int min = 50;
	int max = 150;

	srand(nSysTime);

	while(true)
	{
		if(nNxtButtonPressed == BotaoLaranja){
			NovoValor = 255;
		}
		else{
			NovoValor = 80;
		}
		//NovoValor = (rand() % (max-min)) + min;
		//wait1Msec(77);
	}
}
