#pragma config(Sensor, S1,     0,               sensorSONAR)
#pragma config(Sensor, S2,     1,              sensorSONAR)
#pragma config(Sensor, S3,     2,              sensorSONAR)
#pragma config(Sensor, S4,     3,              sensorI2CHiTechnicColor)
#pragma config(Motor,  motorA,          A,             tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          E,             tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          D,             tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define VelocidadeMax 100
#define kVelocidade 2
#define kAjusteCentro 1

#include "configurarVariaveis.h"
#include "configuracaoManual.h"
#include "atualizarDisplay.h"
//#include "filtrarSensor.h"
#include "filtroTesteCor.h"
#include "tratamentoSensoresCor.h"
#include "monitoramento.h"
#include "movimentacaoXangai.h"
#include "estrategiasXangai.h"

task AtualizarSensores();
task SimularSensores();

task main()
{
	nMotorPIDSpeedCtrl[E] = mtrSpeedReg;
	nMotorPIDSpeedCtrl[D] = mtrSpeedReg;
	bPlaySounds = true;
	UnmuteSound();
	nVolume = 4;
	setBluetoothOn();
	btConnect(1, "NXT");
	clearDebugStream();
	ClearTimer(T1);

	ConfigurarVariaveis();
	Esperar = GerarMenu(Esperar5s, 2);
	EstrategiaSelecionada = GerarMenu(Estrategias, NumEstrategias);
	PressioneStart();

	//StartTask(Monitoramento);
	StartTask(AtualizarDisplay);
	StartTask(AtualizarSensores);
	//StartTask(SimularSensores);
	StartTask(TratarSensores);

	if(Esperar){
		FuncaoEsperar();
	}

	iniciarEstrategia();

	StartTask(Movimentacao);

	//StopTask(EstrategiaPadrao);
	//StatusMotor = Frente;

	while(true){
		print("%d\n",ValorSensor[Acelerometro]);
		wait10Msec(10);
	}
}

//==========================FUNCOES=================================

task AtualizarSensores(){
	bool simular = false;
	while(true){
		FiltrarSensor(SonarEsquerdo, simular);
		FiltrarSensor(SonarDireito, simular);
		FiltrarSensor(SonarCentro, simular);
		NovoValor = SensorValue[S4];
		FiltrarSensor(Acelerometro, simular);
		//ProcessarAcelerometro();
	}
}

task SimularSensores(){
	int min = 50;
	int max = 150;

	srand(nSysTime);

	while(true)
	{
		if(nNxtButtonPressed == BotaoLaranja){
			NovoValor = 255;
		}
		else{
			NovoValor = 80;
		}
		//NovoValor = (rand() % (max-min)) + min;
		//wait1Msec(77);
	}
}
